# Generated by Django 5.2.4 on 2025-07-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_updated_date_alter_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
